kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-produto-pv-volume
  labels:
    type: local
    app: postgres-produto
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-produto-pv-claim
  labels:
    app: postgres-produto
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi