apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-pagamento
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-pagamento
  template:
    metadata:
      labels:
        app: postgres-pagamento
    spec:
      containers:
        - name: postgres-pagamento
          image: postgres:10.1
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-pagamento-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-pagamento-db
      volumes:
        - name: postgres-pagamento-db
          persistentVolumeClaim:
            claimName: postgres-pagamento-pv-claim