apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-produto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-produto
  template:
    metadata:
      labels:
        app: mongodb-produto
    spec:
      containers:
        - name: mongodb-produto
          image: mongo:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 27017
          envFrom:
            - configMapRef:
                name: mongodb-produto-config
          volumeMounts:
            - mountPath: /data/db
              name: mongodb-produto-db
      volumes:
        - name: mongodb-produto-db
          persistentVolumeClaim:
            claimName: mongodb-produto-pv-claim