apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-pedido
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-pedido
  template:
    metadata:
      labels:
        app: postgres-pedido
    spec:
      containers:
        - name: postgres-pedido
          image: postgres:10.1
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-pedido-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-pedido-db
      volumes:
        - name: postgres-pedido-db
          persistentVolumeClaim:
            claimName: postgres-pedido-pv-claim